In [2]:
# 练习一下einsum
import torch
from einops import einsum, rearrange

In [3]:
in_features = 10
out_features = 11
x = torch.randn(in_features)
W = torch.randn(out_features, in_features)
x @ W.T, W @ x, einsum(W, x, 'out in, in -> out')

/Users/toki/Code/Courses/cs336/cs336-proj1/.venv/lib/python3.12/site-packages/einops/parsing.py:137: RuntimeWarning: It is discouraged to use axes names that are keywords: in
  warnings.warn("It is discouraged to use axes names that are keywords: {}".format(name), RuntimeWarning)


(tensor([-7.8283, -2.5501,  1.4421, -3.2527,  8.5236, -7.6683,  3.3539, -3.2002,
          1.8284, -2.6300,  7.5920]),
 tensor([-7.8283, -2.5501,  1.4421, -3.2527,  8.5236, -7.6683,  3.3539, -3.2002,
          1.8284, -2.6300,  7.5920]),
 tensor([-7.8283, -2.5501,  1.4421, -3.2527,  8.5236, -7.6683,  3.3539, -3.2002,
          1.8284, -2.6300,  7.5920]))

In [4]:
batch =6
seq = 5
dim = 4
hid = torch.randn(batch, seq, dim)
A = torch.randn(dim*4, dim)
(hid @ A.T).shape, einsum(hid, A, 'b s d, o d -> b s o').shape

(torch.Size([6, 5, 16]), torch.Size([6, 5, 16]))

In [5]:
hid.sum(dim=-1)

tensor([[ 2.7733, -3.4934,  3.8144, -2.2120,  0.5929],
        [ 1.0028,  0.7392,  0.9369, -1.5802,  2.3668],
        [-3.5127, -1.0670, -1.5848, -3.2522,  0.8101],
        [ 0.7875, -1.0146,  0.7517,  2.2313, -0.4604],
        [-0.5497,  1.6044,  1.6652, -0.3808,  2.7696],
        [-2.2482,  1.2935,  1.5369, -0.8542, -1.3654]])

In [10]:
a = torch.arange(0,10)
b = torch.arange(0, -12, -1)
c = a.unsqueeze(1) @ b.unsqueeze(0)
c.shape

torch.Size([10, 12])

In [12]:
theta = 10000
d_k = 100
max_seq_len = 200
inv_freqs = theta ** (- torch.arange(0, d_k, 2, dtype=torch.float32) / d_k)
        
# 构建频率和位置
pos = torch.arange(0, max_seq_len, dtype=torch.float32) # (max_seq_len)

# 构建sin和cos
# 我们需要的sin和cos的形状是什么?
# 需要能和 x 进行计算, 那么他们都是2d向量
# freqs = pos.unsqueeze(1) @ inv_freqs.unsqueeze(0)
# 轮椅写法
freqs = einsum(pos, inv_freqs, 's, d -> s d')

cos = torch.cos(freqs) # seq d/2
sin = torch.sin(freqs) # seq d/2
sin, cos

(tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 8.4147e-01,  7.3912e-01,  6.3795e-01,  ...,  1.7378e-04,
           1.4454e-04,  1.2023e-04],
         [ 9.0930e-01,  9.9570e-01,  9.8254e-01,  ...,  3.4756e-04,
           2.8909e-04,  2.4045e-04],
         ...,
         [ 7.9581e-01,  4.7472e-01, -9.3284e-01,  ...,  3.4228e-02,
           2.8471e-02,  2.3682e-02],
         [-7.9579e-02,  9.7029e-01, -9.4820e-01,  ...,  3.4402e-02,
           2.8616e-02,  2.3803e-02],
         [-8.8180e-01,  8.3239e-01, -5.2755e-01,  ...,  3.4575e-02,
           2.8760e-02,  2.3923e-02]]),
 tensor([[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
         [ 0.5403,  0.6736,  0.7701,  ...,  1.0000,  1.0000,  1.0000],
         [-0.4161, -0.0926,  0.1860,  ...,  1.0000,  1.0000,  1.0000],
         ...,
         [-0.6056,  0.8801, -0.3603,  ...,  0.9994,  0.9996,  0.9997],
         [-0.9968,  0.2419,  0.3177,  ...,  0.9994,  0.9

In [14]:
x.max(-1, keepdim=True).values

tensor([1.9139])