In [1]:
# 练习一下einsum
import torch
from einops import einsum, rearrange

In [5]:
in_features = 10
out_features = 11
x = torch.randn(in_features)
W = torch.randn(out_features, in_features)
x @ W.T, W @ x, einsum(W, x, 'out in, in -> out')

/home/wly/szl_all_code/cs336-all/assignment1/.venv/lib/python3.12/site-packages/einops/parsing.py:137: RuntimeWarning: It is discouraged to use axes names that are keywords: in
  warnings.warn("It is discouraged to use axes names that are keywords: {}".format(name), RuntimeWarning)


(tensor([ 0.3435,  0.2490, -1.1707, -3.2284,  6.9927,  0.6349,  3.0539,  1.1426,
          4.9057,  0.0884, -0.6065]),
 tensor([ 0.3435,  0.2490, -1.1707, -3.2284,  6.9927,  0.6349,  3.0539,  1.1426,
          4.9057,  0.0884, -0.6065]),
 tensor([ 0.3435,  0.2490, -1.1707, -3.2284,  6.9927,  0.6349,  3.0539,  1.1426,
          4.9057,  0.0884, -0.6065]))

In [11]:
batch =6
seq = 5
dim = 4
hid = torch.randn(batch, seq, dim)
A = torch.randn(dim*4, dim)
(hid @ A.T).shape, einsum(hid, A, 'b s d, o d -> b s o').shape

(torch.Size([6, 5, 16]), torch.Size([6, 5, 16]))

In [19]:
hid.sum(dim=-1)

tensor([[-2.7660, -4.1865, -2.3136, -1.7494,  6.0439],
        [ 0.6716, -0.7842,  1.5666,  0.8562, -0.3512],
        [ 2.8595, -2.7209,  1.5959, -0.4007,  1.9569],
        [ 0.4891, -3.1763,  0.7137,  0.8654, -1.9769],
        [-0.3604,  0.1505,  1.8963, -5.7916, -1.6728],
        [-0.3933,  0.7322, -0.9004,  3.9601,  2.3599]])